const movies = [
  {
    title: "Cloudy With A Chance Of Meatballs (2009)",
    src: "https://archive.org/download/cloudy.with.a.-chance.of.-meatballs.-2009.1080p.-blu-ray.-h-264.-aac-rarbg/Cloudy.with.a.Chance.of.Meatballs.2009.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Cloudy With A Chance Of Meatballs 2 (2013)",
    src: "https://archive.org/download/cloudy.with.a.-chance.of.-meatballs.-2.2013.1080p.-blu-ray.-h-264.-aac-rarbg/Cloudy.with.a.Chance.of.Meatballs.2.2013.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Smallfoot (2018)",
    src: "https://archive.org/download/smallfoot.-2018.1080p.-blu-ray.x-265-rarbg/Smallfoot.2018.1080p.BluRay.x265-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Madagascar (2005)",
    src: "https://archive.org/download/madagascar.-2005.1080p.-blu-ray.-h-264.-aac-rarbg/Madagascar.2005.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Bean (1997)",
    src: "https://archive.org/download/bean.-1997.1080p.-blu-ray.-h-264.-aac-rarbg/Bean.1997.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Johnny English (2003)",
    src: "https://archive.org/download/johnny.-english.-2003.1080p.-blu-ray.-h-264.-aac-rarbg/Johnny.English.2003.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Mr Bean S Holiday (2007)",
    src: "https://archive.org/download/mr.-bean.s.-holiday.-2007.1080p.-blu-ray.-h-264.-aac-rarbg/Mr.Bean.s.Holiday.2007.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Johnny English Strikes Again (2018)",
    src: "https://archive.org/download/johnny.-english.-strikes.-again.-2018.1080p.-blu-ray.-h-264.-aac-rarbg/Johnny.English.Strikes.Again.2018.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "TheLordoftheRings19781080pBluRayH264AAC Rarbg (1978)",
    src: "https://archive.org/download/the-lordofthe-rings-19781080p-blu-ray-h-264-aac-rarbg/TheLordoftheRings19781080pBluRayH264AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Ernest Goes To Camp (1987)",
    src: "https://archive.org/download/ernest.-goes.-to.-camp.-1987.1080p.-blu-ray.x-265-rarbg-x-264/Ernest.Goes.To.Camp.1987.1080p.BluRay.x265-RARBG_x264.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Mad Max (1979)",
    src: "https://archive.org/download/mad.-max.-1979.1080p.-blu-ray.x-265-rarbg/Mad.Max.1979.1080p.BluRay.x265-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Dantes Inferno An Animated Epic (2010)",
    src: "https://archive.org/download/dantes.-inferno.-an.-animated.-epic.-2010.1080p.-blu-ray.x-265-rarbg/Dantes.Inferno.An.Animated.Epic.2010.1080p.BluRay.x265-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "The Adventures Of Tintin (2011)",
    src: "https://archive.org/download/the.-adventures.of.-tintin.-2011.1080p.-blu-ray.-h-264.-aac-rarbg/The.Adventures.of.Tintin.2011.1080p.BluRay.H264.AAC-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "The Life And Adventures Of Santa Claus (1985)",
    src: "https://archive.org/download/the.-life.and.-adventures.of.-santa.-claus.-1985.1080p.-webrip.x-265-rarbg/The%20Life%20and%20Adventures%20of%20Santa%20Claus%20%281985%29%201080p/The.Life.and.Adventures.of.Santa.Claus.1985.1080p.WEBRip.x265-RARBG.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Charlie And The Chocolate Factory (2005)",
    src: "https://archive.org/download/charlie-and-the-chocolate-factory-2005-720p-br-rip_202607/Charlie_and_the_Chocolate_Factory_2005_720p_BrRip.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
  {
    title: "Honey, I Shrunk The Kids",
    src: "https://archive.org/download/honey-i-shrunk-the-kids-laserdisc-rf-capture/Honey%2C%20I%20Shrunk%20the%20Kids.mp4",
    thumb: "https://placehold.co/200x300?text=No+Image",
    subtitle: "https://raw.githubusercontent.com/harish-kumar-kp/showreel/main/VIdOTT/subtitles/Dummy_Subtitles.srt",
    category: "unknown",
  },
];
